#!/usr/bin/env python3
"""Generate the 'Supported radios' table in site/index.html.

The row set is authoritative from ``radios/*/capabilities.json``. Presentation
detail that capabilities.json deliberately does not model (vendor blurb, 'hw'
badges, third-party import columns, the dmrconf/p64tool backends) comes from
``site/radios.json``.

The point of this script is the failure mode: if a radio is added under
``radios/`` and nobody touches the site, generation *fails* instead of quietly
producing a table that is missing a radio.

Usage::

    python tools/gen_radio_table.py            # rewrite site/index.html
    python tools/gen_radio_table.py --check    # exit 1 if the file is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RADIOS_DIR = REPO_ROOT / "radios"
SITE_DIR = REPO_ROOT / "site"
INDEX_HTML = SITE_DIR / "index.html"
RADIOS_JSON = SITE_DIR / "radios.json"

BEGIN_MARKER = "<!-- BEGIN generated by tools/gen_radio_table.py -->"
END_MARKER = "<!-- END generated by tools/gen_radio_table.py -->"

ROW_INDENT = " " * 14
CELL_INDENT = " " * 16

HW_BADGE = '<span class="hw" title="Verified on a physical radio">hw</span>'

# Backends that a capabilities block implies. If a radio declares one of these
# blocks it is the backend, and site/radios.json is not allowed to disagree.
BLOCK_BACKENDS = {"chirp": "chirp-writer", "benlink": "benlink"}

ARTIFACT_COLUMNS = ("chirp_csv", "qdmr_yaml", "p64_toml", "oem_cps")

# How a capabilities mode has to appear in the displayed Modes cell. AM is
# receive-only on every radio we support (airband / FM broadcast rx_only bands).
MODE_TOKENS = {"DMR": "DMR", "FM": "FM", "AM": "AM RX"}


class GenError(RuntimeError):
    """A data problem the author has to fix by hand."""


# --------------------------------------------------------------------------
# loading
# --------------------------------------------------------------------------


def load_capabilities() -> dict[str, dict]:
    if not RADIOS_DIR.is_dir():
        raise GenError(f"no radios directory at {RADIOS_DIR}")

    caps: dict[str, dict] = {}
    for path in sorted(RADIOS_DIR.glob("*/capabilities.json")):
        data = json.loads(path.read_text())
        radio_id = data.get("id")
        if not radio_id:
            raise GenError(f"{path} has no 'id'")
        if radio_id != path.parent.name:
            raise GenError(
                f"{path}: id {radio_id!r} does not match directory "
                f"{path.parent.name!r}"
            )
        caps[radio_id] = data

    if not caps:
        raise GenError(f"no capabilities.json files under {RADIOS_DIR}")
    return caps


def load_rows() -> list[dict]:
    data = json.loads(RADIOS_JSON.read_text())
    rows = data.get("rows")
    if not isinstance(rows, list) or not rows:
        raise GenError(f"{RADIOS_JSON} has no 'rows' list")
    return rows


# --------------------------------------------------------------------------
# derivation from capabilities
# --------------------------------------------------------------------------


def render_modes(cap: dict, declared: list | None) -> str:
    """Render the Modes cell, cross-checked against capabilities.json.

    The displayed cell is a claim about the *radio*; ``capabilities.modes`` is
    the set of modes codeplugger will emit for it, and at least one radio
    (baofeng_uv5r_mini) documents its ``modes`` as emission policy rather than
    a hardware fact. So the cell is declared in site/radios.json and validated
    here: it must cover every mode capabilities.json declares, and may not
    invent tokens.
    """
    if not declared:
        raise GenError(f"{cap['id']}: site/radios.json entry has no 'modes'")

    unknown = [m for m in declared if m not in MODE_TOKENS.values()]
    if unknown:
        raise GenError(
            f"{cap['id']}: unknown mode token(s) {unknown}; allowed: "
            + ", ".join(sorted(set(MODE_TOKENS.values())))
        )

    caps_modes = cap.get("modes") or []
    bad = sorted(set(caps_modes) - set(MODE_TOKENS))
    if bad:
        raise GenError(f"{cap['id']}: unhandled capabilities mode(s) {bad}")

    missing = sorted(
        MODE_TOKENS[m] for m in caps_modes if MODE_TOKENS[m] not in declared
    )
    if missing:
        raise GenError(
            f"{cap['id']}: capabilities.json declares mode(s) the site table "
            f"does not show: {missing}"
        )

    if "AM RX" in declared and not any(
        b.get("rx_only") for b in cap.get("bands") or []
    ):
        raise GenError(
            f"{cap['id']}: table shows 'AM RX' but capabilities.json has no "
            "rx_only band"
        )

    order = ["DMR", "FM", "AM RX"]
    return " · ".join(sorted(declared, key=order.index))


def derive_backend(cap: dict, declared: str | None) -> str | None:
    """Resolve the headless-write backend, cross-checking capabilities."""
    implied = [
        backend for block, backend in BLOCK_BACKENDS.items() if block in cap
    ]
    if len(implied) > 1:
        raise GenError(
            f"{cap['id']}: declares multiple write blocks {implied}; the table "
            "has one Headless write column"
        )

    if implied:
        backend = implied[0]
        if declared is not None and declared != backend:
            raise GenError(
                f"{cap['id']}: site/radios.json says backend {declared!r} but "
                f"capabilities.json implies {backend!r}"
            )
        return backend

    if declared in BLOCK_BACKENDS.values():
        raise GenError(
            f"{cap['id']}: site/radios.json claims backend {declared!r} but "
            "capabilities.json has no matching block"
        )
    return declared


# --------------------------------------------------------------------------
# cells
# --------------------------------------------------------------------------


def normalize_cell(value, *, where: str) -> dict:
    if isinstance(value, bool):
        return {"supported": value, "note": None, "hw": False}
    if isinstance(value, dict):
        if "supported" not in value:
            raise GenError(f"{where}: cell object needs 'supported'")
        extra = set(value) - {"supported", "note", "hw", "backend"}
        if extra:
            raise GenError(f"{where}: unknown cell key(s) {sorted(extra)}")
        return {
            "supported": bool(value["supported"]),
            "note": value.get("note"),
            "hw": bool(value.get("hw", False)),
        }
    raise GenError(f"{where}: cell must be a bool or an object, got {type(value).__name__}")


def render_cell(cell: dict) -> str:
    supported = cell["supported"]
    cls = "yes" if supported else "no"
    glyph = "✓" if supported else "—"

    body = f'<span aria-hidden="true">{glyph}</span>'
    if cell["note"]:
        body += f' {cell["note"]}'
    if cell["hw"]:
        body += HW_BADGE
    if not cell["note"] and not cell["hw"]:
        label = "Supported" if supported else "Not supported"
        body += f'<span class="sr">{label}</span>'

    return f'<td class="{cls}">{body}</td>'


def render_row(cap: dict, row: dict) -> list[str]:
    radio_id = cap["id"]
    vendor = row.get("vendor")
    if not vendor:
        raise GenError(f"{radio_id}: site/radios.json entry has no 'vendor' blurb")

    headless_raw = row.get("headless")
    if headless_raw is None:
        raise GenError(f"{radio_id}: site/radios.json entry has no 'headless' cell")
    declared_backend = (
        headless_raw.get("backend") if isinstance(headless_raw, dict) else None
    )
    headless = normalize_cell(headless_raw, where=f"{radio_id}.headless")
    backend = derive_backend(cap, declared_backend)

    if headless["supported"]:
        if not backend:
            raise GenError(
                f"{radio_id}: headless write is supported but no backend could "
                "be derived; add a capabilities block or a 'backend' key"
            )
        if headless["note"]:
            raise GenError(
                f"{radio_id}: headless 'note' is reserved for the backend name "
                "(it is derived)"
            )
        headless["note"] = backend
    elif backend:
        raise GenError(
            f"{radio_id}: headless write is not supported but backend "
            f"{backend!r} was derived"
        )

    cells = {}
    for column in ARTIFACT_COLUMNS:
        if column not in row:
            raise GenError(f"{radio_id}: site/radios.json entry is missing {column!r}")
        cells[column] = normalize_cell(row[column], where=f"{radio_id}.{column}")

    if "chirp" in cap and not cells["chirp_csv"]["supported"]:
        raise GenError(
            f"{radio_id}: capabilities.json has a 'chirp' block but the CHIRP "
            "import column says unsupported"
        )

    name = cap["name"]
    lines = [
        f"{ROW_INDENT}<tr>",
        f'{CELL_INDENT}<th scope="row">{name} '
        f'<span class="vendor">{vendor}</span></th>',
        f'{CELL_INDENT}<td class="modes">{render_modes(cap, row.get("modes"))}</td>',
    ]
    lines += [CELL_INDENT + render_cell(cells[c]) for c in ARTIFACT_COLUMNS]
    lines.append(CELL_INDENT + render_cell(headless))
    lines.append(f"{ROW_INDENT}</tr>")
    return lines


# --------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------


def build_tbody() -> str:
    caps = load_capabilities()
    rows = load_rows()

    seen: list[str] = []
    for row in rows:
        radio_id = row.get("id")
        if not radio_id:
            raise GenError(f"{RADIOS_JSON}: a row has no 'id'")
        if radio_id in seen:
            raise GenError(f"{RADIOS_JSON}: duplicate row for {radio_id!r}")
        seen.append(radio_id)

    missing = sorted(set(caps) - set(seen))
    if missing:
        raise GenError(
            "radios present under radios/ but missing from site/radios.json: "
            + ", ".join(missing)
            + "\n  -> every radio has to appear in the site table; add a row."
        )

    orphaned = sorted(set(seen) - set(caps))
    if orphaned:
        raise GenError(
            "site/radios.json lists radios with no radios/<id>/capabilities.json: "
            + ", ".join(orphaned)
        )

    lines: list[str] = []
    for row in rows:
        lines += render_row(caps[row["id"]], row)
    return "\n".join(lines)


def render_index(current: str) -> str:
    try:
        head, rest = current.split(BEGIN_MARKER, 1)
        _, tail = rest.split(END_MARKER, 1)
    except ValueError as exc:
        raise GenError(
            f"{INDEX_HTML} is missing the {BEGIN_MARKER} / {END_MARKER} markers"
        ) from exc

    return f"{head}{BEGIN_MARKER}\n{build_tbody()}\n{ROW_INDENT}{END_MARKER}{tail}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if site/index.html is not what the generator would write",
    )
    args = parser.parse_args(argv)

    current = INDEX_HTML.read_text()
    updated = render_index(current)

    if args.check:
        if current != updated:
            print(
                "site/index.html is stale -- run: python tools/gen_radio_table.py",
                file=sys.stderr,
            )
            return 1
        print("site/index.html radio table is up to date")
        return 0

    if current == updated:
        print("site/index.html radio table already up to date")
        return 0

    INDEX_HTML.write_text(updated)
    print(f"rewrote radio table in {INDEX_HTML.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except GenError as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(2) from None
